### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by kairos03** [polyaxon/polyaxon-chart#53]
Hi,

i'm installing polyaxon with helm all other pods is available but api-server and scheduler causing error.
Any one help me?

OS : ubuntu 18.04.3
k8s: 1.15.0
helm: 2.16.1

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 35, in check_url_namespaces_unique
    if not getattr(settings, 'ROOT_URLCONF', None):
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/polyaxon/polyaxon/polyaxon/__init__.py", line 1, in <module>
    from polyaxon.celery_api import app
  File "/polyaxon/polyaxon/polyaxon/celery_api.py", line 3, in <module>
    from celery import Celery, states
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 23, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python3.7/site-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.7/site-packages/amqp/__init__.py", line 33, in <module>
    from .connection import Connection  # noqa
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 21, in <module>
    from .transport import Transport
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/polyaxon/polyaxon/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/polyaxon/polyaxon/polyaxon/__init__.py", line 1, in <module>
    from polyaxon.celery_api import app
  File "/polyaxon/polyaxon/polyaxon/celery_api.py", line 3, in <module>
    from celery import Celery, states
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 23, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python3.7/site-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.7/site-packages/amqp/__init__.py", line 33, in <module>
    from .connection import Connection  # noqa
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 21, in <module>
    from .transport import Transport
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
Running...
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/celery/__main__.py", line 15, in main
    from celery.bin.celery import main as _main
  File "/usr/local/lib/python3.7/site-packages/celery/bin/__init__.py", line 2, in <module>
    from .base import Option
  File "/usr/local/lib/python3.7/site-packages/celery/bin/base.py", line 16, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency, signals
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 23, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python3.7/site-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.7/site-packages/amqp/__init__.py", line 33, in <module>
    from .connection import Connection  # noqa
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 21, in <module>
    from .transport import Transport
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)

```

**Comment by mouradmourafiq** [comment]
Are you using minikube?
